import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import { Montserrat } from 'next/font/google';
import StoreProvider from "./StoreProvider";
import dynamic from "next/dynamic";
import 'bootstrap/dist/css/bootstrap.css';
import "./globals.css";
import '@icon/icofont/icofont.css';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import Toast from "@/Components/ToastContainer";


const Header = dynamic(() => import('@/Components/Header/Header'))
const Footer = dynamic(() => import('@/Components/Footer/Footer'))

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  subsets: ['latin'], // Choose the subset (e.g., 'latin')
  variable: '--font-montserrat', // Optional: Add a CSS variable for the font
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'], // Include specific weights
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ['400', '700'],
  style: ['normal', 'italic'],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* <link rel="preconnect" href="https://fonts.googleapis.com" /> */}
        {/* <link rel="preconnect" href="https://fonts.gstatic.com"/> */}
        {/* <link href="https://fonts.googleapis.com/css2?family=Playwrite+IN:wght@100..400&display=swap" rel="stylesheet"> </link> */}

        {/* <link rel="preconnect" href="https://fonts.googleapis.com" /> */}
        {/* <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin /> */}
        {/* <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@100,400&display=swap" rel="stylesheet" /> */}

        {/* <link rel="preconnect" href="https://fonts.googleapis.com"/> */}
        {/* <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin/> */}
        {/* <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet"></link> */}


      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} ${poppins.className} antialiased`}
      >

        {/* {children} */}
        <StoreProvider>
          <Header />
          {children}
          <Toast></Toast>
          <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}
